// Code generated by "stringer -type=MessageType"; DO NOT EDIT.

package protocol

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TypeUnknown-0]
	_ = x[TypeP2P-1]
	_ = x[TypeBroadcast-2]
	_ = x[TypeQueueTask-3]
	_ = x[TypeRegister-4]
	_ = x[TypeReport-5]
}

const _MessageType_name = "TypeUnknownTypeP2PTypeBroadcastTypeQueueTaskTypeRegisterTypeReport"

var _MessageType_index = [...]uint8{0, 11, 18, 31, 44, 56, 66}

func (i MessageType) String() string {
	if i >= MessageType(len(_MessageType_index)-1) {
		return "MessageType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MessageType_name[_MessageType_index[i]:_MessageType_index[i+1]]
}
